# Generated by Django 5.0.1 on 2024-03-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('nome_do_dispositivo', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
