# Generated by Django 5.0.1 on 2024-04-04 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0003_scanner_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='ativo',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=3),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porta', models.IntegerField()),
                ('nome_servico', models.CharField(max_length=100)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptcc.dispositivo')),
            ],
        ),
    ]
