# Generated by Django 5.0.1 on 2024-04-04 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0004_alter_scanner_ativo_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
