# Generated by Django 5.0.1 on 2024-04-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0005_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('porta', models.IntegerField()),
                ('nome_servico', models.CharField(max_length=100)),
            ],
        ),
    ]
