# Generated by Django 5.0.1 on 2024-04-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0006_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='nome_servico',
        ),
        migrations.RemoveField(
            model_name='service',
            name='porta',
        ),
        migrations.AddField(
            model_name='service',
            name='lista_de_coisas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
