# Generated by Django 5.0.1 on 2024-04-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0007_remove_service_nome_servico_remove_service_porta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='ip',
        ),
        migrations.AddField(
            model_name='service',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apptcc.dispositivo'),
        ),
    ]
