# Generated by Django 5.0.1 on 2024-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0009_remove_service_dispositivo_service_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ip',
            field=models.CharField(max_length=16),
        ),
    ]
