# Generated by Django 5.0.1 on 2024-04-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0010_alter_service_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
