# Generated by Django 5.0.4 on 2024-05-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0013_remove_service_ip_service_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='off',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
