# Generated by Django 5.0.1 on 2024-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0014_offline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offline',
        ),
        migrations.AddField(
            model_name='scanner',
            name='off',
            field=models.CharField(default=5, max_length=16),
            preserve_default=False,
        ),
    ]
