# Generated by Django 5.0.1 on 2024-06-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0015_remove_scanner_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(max_length=18)),
                ('ip', models.CharField(max_length=16)),
            ],
        ),
    ]
