# Generated by Django 5.0.1 on 2024-04-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0015_delete_offline_scanner_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanner',
            name='off',
        ),
    ]
