# Generated by Django 5.0.1 on 2024-06-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptcc', '0016_offline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=50),
        ),
    ]
